"""Constants for the simplified 2026 REBUILT simulator.

The dimensions here are intentionally coarse. They preserve the official
REBUILT concepts that matter to the RL task: FUEL collection, active HUB
windows, HUB keepout, alliance-zone shooting, and simple FUEL flight.
"""

from __future__ import annotations

import math

FIELD_LENGTH_M = 16.54
FIELD_WIDTH_M = 8.07
FIELD_DIAGONAL_M = math.hypot(FIELD_LENGTH_M, FIELD_WIDTH_M)
HALF_FIELD_LENGTH_M = FIELD_LENGTH_M / 2.0

AUTO_DURATION_S = 20.0
TELEOP_DURATION_S = 140.0
MATCH_DURATION_S = AUTO_DURATION_S + TELEOP_DURATION_S
TRANSITION_SHIFT_DURATION_S = 10.0
ALLIANCE_SHIFT_DURATION_S = 25.0
ENDGAME_DURATION_S = 30.0
ENDGAME_START_S = MATCH_DURATION_S - ENDGAME_DURATION_S
CONTROL_PERIOD_S = 0.1

ROBOT_RADIUS_M = 0.48
MAX_LINEAR_SPEED_MPS = 4.5
MAX_ANGULAR_SPEED_RADPS = 7.0
MAX_LINEAR_ACCEL_MPS2 = 7.0
MAX_ANGULAR_ACCEL_RADPS2 = 14.0

INTAKE_RADIUS_M = 0.55
SCORE_RADIUS_M = 3.20
SCORE_TRIGGER_RADIUS_M = SCORE_RADIUS_M
SCORE_HEADING_TOLERANCE_RAD = math.radians(80.0)
INTAKE_DURATION_S = 0.18
FUEL_SHOT_RATE_BPS = 15.0
SCORE_DURATION_S = 1.0 / FUEL_SHOT_RATE_BPS
MECHANISM_LINEAR_SETTLE_MPS = 0.45
MECHANISM_ANGULAR_SETTLE_RADPS = 0.85
FUEL_SHOT_SPEED_MPS = 8.0
FUEL_SHOT_CAPTURE_RADIUS_M = 0.35
FUEL_SHOT_MAX_AGE_S = 2.5
FUEL_SHOT_GRAVITY_MPS2 = 9.81
FUEL_SOURCE_HEIGHT_M = 0.09
FUEL_HELD_HEIGHT_M = 0.45
FUEL_SHOT_LAUNCH_HEIGHT_M = 0.62
FUEL_HUB_TARGET_HEIGHT_M = 1.75
FUEL_HUB_CAPTURE_HEIGHT_TOLERANCE_M = 0.70
FUEL_RETURN_SCATTER_RADIUS_M = 1.25

BLUE_ALLIANCE_ZONE_DEPTH_M = 4.03
BLUE_TRENCH_LINE_X_M = 6.12
TRENCH_CORRIDOR_WIDTH_M = 1.75
BLUE_HUB_CENTER = (BLUE_ALLIANCE_ZONE_DEPTH_M, FIELD_WIDTH_M / 2.0)
HUB_OBSTACLE_RADIUS_M = 0.86
HUB_CLEARANCE_M = 0.02
HUB_SCORING_RADIUS_M = HUB_OBSTACLE_RADIUS_M + ROBOT_RADIUS_M + 0.60
BLUE_TOWER_POSE = (1.55, FIELD_WIDTH_M / 2.0)

# (name, x, y, starting fuel). A negative count means effectively unlimited
# human-player supply for this simplified simulator.
BLUE_FUEL_SOURCES = (
    ("neutral_center", HALF_FIELD_LENGTH_M, FIELD_WIDTH_M / 2.0, 100),
)

BLUE_MIDFIELD_SWEEP_POINTS = (
    (HALF_FIELD_LENGTH_M - 0.85, 2.00),
    (HALF_FIELD_LENGTH_M + 0.85, 2.00),
    (HALF_FIELD_LENGTH_M + 0.85, 3.05),
    (HALF_FIELD_LENGTH_M - 0.85, 3.05),
    (HALF_FIELD_LENGTH_M - 0.85, 4.05),
    (HALF_FIELD_LENGTH_M + 0.85, 4.05),
    (HALF_FIELD_LENGTH_M + 0.85, 5.05),
    (HALF_FIELD_LENGTH_M - 0.85, 5.05),
    (HALF_FIELD_LENGTH_M - 0.85, FIELD_WIDTH_M - 2.00),
    (HALF_FIELD_LENGTH_M + 0.85, FIELD_WIDTH_M - 2.00),
)

FUEL_POINTS_AUTO = 1
FUEL_POINTS_TELEOP = 1
DEFAULT_MIDFIELD_FUEL_COUNT = 100
DEFAULT_ROBOT_FUEL_CAPACITY = 50
DEFAULT_MAX_FUEL_SCORED = 100

# Backward-compatible aliases for older scripts/tests that imported the 2025
# names directly.
BLUE_REEF_CENTER = BLUE_HUB_CENTER
REEF_OBSTACLE_RADIUS_M = HUB_OBSTACLE_RADIUS_M
REEF_CLEARANCE_M = HUB_CLEARANCE_M
REEF_SCORING_RADIUS_M = HUB_SCORING_RADIUS_M
BLUE_CORAL_STATIONS = tuple((x, y) for _, x, y, _ in BLUE_FUEL_SOURCES[:2])
SCORING_POINTS_TELEOP = {"FUEL": FUEL_POINTS_TELEOP, "L4": FUEL_POINTS_TELEOP}
SCORING_POINTS_AUTO = {"FUEL": FUEL_POINTS_AUTO, "L4": FUEL_POINTS_AUTO}
DEFAULT_TARGET_LEVEL = "FUEL"
DEFAULT_MAX_CORAL_SCORED = DEFAULT_MAX_FUEL_SCORED
