"""Constants for the simplified REEFSCAPE simulator.

Field dimensions are based on the official 2025 REEFSCAPE manual's nominal
dimensions: approximately 57 ft 6 7/8 in by 26 ft 5 in.
"""

from __future__ import annotations

import math

FIELD_LENGTH_M = 17.55
FIELD_WIDTH_M = 8.05
FIELD_DIAGONAL_M = math.hypot(FIELD_LENGTH_M, FIELD_WIDTH_M)
HALF_FIELD_LENGTH_M = FIELD_LENGTH_M / 2.0

MATCH_DURATION_S = 150.0
CONTROL_PERIOD_S = 0.1

ROBOT_RADIUS_M = 0.48
OTHER_ROBOT_RADIUS_M = ROBOT_RADIUS_M
OTHER_ROBOT_CLEARANCE_M = 0.0
OTHER_ROBOT_SPEED_MPS = 1.35
MAX_LINEAR_SPEED_MPS = 4.5
MAX_ANGULAR_SPEED_RADPS = 7.0
MAX_LINEAR_ACCEL_MPS2 = 7.0
MAX_ANGULAR_ACCEL_RADPS2 = 14.0

INTAKE_RADIUS_M = 0.7
SCORE_RADIUS_M = 0.85
SCORE_TRIGGER_RADIUS_M = 0.20
SCORE_HEADING_TOLERANCE_RAD = math.radians(75.0)
INTAKE_DURATION_S = 0.25
SCORE_DURATION_S = 0.25
MECHANISM_LINEAR_SETTLE_MPS = 0.35
MECHANISM_ANGULAR_SETTLE_RADPS = 0.75

BLUE_REEF_CENTER = (4.50, FIELD_WIDTH_M / 2.0)
REEF_OBSTACLE_RADIUS_M = 1.10
REEF_CLEARANCE_M = 0.02
REEF_SCORING_RADIUS_M = REEF_OBSTACLE_RADIUS_M + ROBOT_RADIUS_M + REEF_CLEARANCE_M

BLUE_CORAL_STATIONS = (
    (0.85, 1.15),
    (0.85, FIELD_WIDTH_M - 1.15),
)

BLUE_SIDE_OTHER_ROBOT_PATH = (
    (1.85, 2.25),
    (3.00, 1.55),
    (5.85, 1.55),
    (6.65, 2.65),
    (6.65, FIELD_WIDTH_M - 2.55),
    (5.85, FIELD_WIDTH_M - 1.55),
    (3.00, FIELD_WIDTH_M - 1.55),
    (1.85, FIELD_WIDTH_M - 2.25),
)

SCORING_POINTS_TELEOP = {
    "L1": 2,
    "L2": 3,
    "L3": 4,
    "L4": 5,
}

SCORING_POINTS_AUTO = {
    "L1": 3,
    "L2": 4,
    "L3": 6,
    "L4": 7,
}

DEFAULT_TARGET_LEVEL = "L4"
DEFAULT_MAX_CORAL_SCORED = 12
