// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EvaluateArtifact(arg1:string):Promise<void>;

export function GetState():Promise<main.StateResponse>;

export function OpenAdvantageScope():Promise<void>;

export function OpenFolder():Promise<void>;

export function ReplayArtifact(arg1:string):Promise<void>;

export function RunAction(arg1:string):Promise<void>;

export function RunCLI(arg1:string):Promise<void>;

export function StartSmokeRun():Promise<void>;

export function StartTraining(arg1:main.TrainConfig):Promise<void>;

export function Stop():Promise<void>;
