// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EvaluateArtifact(arg1) {
  return window['go']['main']['App']['EvaluateArtifact'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenAdvantageScope() {
  return window['go']['main']['App']['OpenAdvantageScope']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReplayArtifact(arg1) {
  return window['go']['main']['App']['ReplayArtifact'](arg1);
}

export function RunAction(arg1) {
  return window['go']['main']['App']['RunAction'](arg1);
}

export function RunCLI(arg1) {
  return window['go']['main']['App']['RunCLI'](arg1);
}

export function StartSmokeRun() {
  return window['go']['main']['App']['StartSmokeRun']();
}

export function StartTraining(arg1) {
  return window['go']['main']['App']['StartTraining'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
